export const blogCards = [
  {
    title: `Elevating your risk strategy: spektr's solution to smarter decisions`,
    date: 'Oct 4, 2023',
    category: '/product',
    text: `In today's rapidly evolving financial landscape, companies face numerous challenges when it comes to risk management and compliance.`,
    thumbnail: '/images/Home/Blog/1.png',
  },
  {
    title: `It’s time to conduct due diligence differently.`,
    date: 'Oct 4, 2023',
    category: '/product',
    text: `In today's rapidly evolving financial landscape, companies face numerous challenges when it comes to risk management and compliance.`,
    thumbnail: '/images/Home/Blog/2.png',
  },
  {
    title: `It’s time to conduct due diligence differently.`,
    date: 'Oct 4, 2023',
    category: '/product',
    text: `In today's rapidly evolving financial landscape, companies face numerous challenges when it comes to risk management and compliance.`,
    thumbnail: '/images/Home/Blog/3.png',
  },
  {
    title: `Elevating your risk strategy: spektr's solution to smarter decisions`,
    date: 'Oct 4, 2023',
    category: '/product',
    text: `In today's rapidly evolving financial landscape, companies face numerous challenges when it comes to risk management and compliance.`,
    thumbnail: '/images/Home/Blog/1.png',
  },
  {
    title: `It’s time to conduct due diligence differently.`,
    date: 'Oct 4, 2023',
    category: '/product',
    text: `In today's rapidly evolving financial landscape, companies face numerous challenges when it comes to risk management and compliance.`,
    thumbnail: '/images/Home/Blog/2.png',
  },
  {
    title: `It’s time to conduct due diligence differently.`,
    date: 'Oct 4, 2023',
    category: '/product',
    text: `In today's rapidly evolving financial landscape, companies face numerous challenges when it comes to risk management and compliance.`,
    thumbnail: '/images/Home/Blog/3.png',
  },
  {
    title: `Elevating your risk strategy: spektr's solution to smarter decisions`,
    date: 'Oct 4, 2023',
    category: '/product',
    text: `In today's rapidly evolving financial landscape, companies face numerous challenges when it comes to risk management and compliance.`,
    thumbnail: '/images/Home/Blog/1.png',
  },
  {
    title: `It’s time to conduct due diligence differently.`,
    date: 'Oct 4, 2023',
    category: '/product',
    text: `In today's rapidly evolving financial landscape, companies face numerous challenges when it comes to risk management and compliance.`,
    thumbnail: '/images/Home/Blog/2.png',
  },
  {
    title: `It’s time to conduct due diligence differently.`,
    date: 'Oct 4, 2023',
    category: '/product',
    text: `In today's rapidly evolving financial landscape, companies face numerous challenges when it comes to risk management and compliance.`,
    thumbnail: '/images/Home/Blog/3.png',
  },
  {
    title: `Elevating your risk strategy: spektr's solution to smarter decisions`,
    date: 'Oct 4, 2023',
    category: '/product',
    text: `In today's rapidly evolving financial landscape, companies face numerous challenges when it comes to risk management and compliance.`,
    thumbnail: '/images/Home/Blog/1.png',
  },
  {
    title: `It’s time to conduct due diligence differently.`,
    date: 'Oct 4, 2023',
    category: '/product',
    text: `In today's rapidly evolving financial landscape, companies face numerous challenges when it comes to risk management and compliance.`,
    thumbnail: '/images/Home/Blog/2.png',
  },
  {
    title: `It’s time to conduct due diligence differently.`,
    date: 'Oct 4, 2023',
    category: '/product',
    text: `In today's rapidly evolving financial landscape, companies face numerous challenges when it comes to risk management and compliance.`,
    thumbnail: '/images/Home/Blog/3.png',
  },
  {
    title: `Elevating your risk strategy: spektr's solution to smarter decisions`,
    date: 'Oct 4, 2023',
    category: '/product',
    text: `In today's rapidly evolving financial landscape, companies face numerous challenges when it comes to risk management and compliance.`,
    thumbnail: '/images/Home/Blog/1.png',
  },
  {
    title: `It’s time to conduct due diligence differently.`,
    date: 'Oct 4, 2023',
    category: '/product',
    text: `In today's rapidly evolving financial landscape, companies face numerous challenges when it comes to risk management and compliance.`,
    thumbnail: '/images/Home/Blog/2.png',
  },
  {
    title: `It’s time to conduct due diligence differently.`,
    date: 'Oct 4, 2023',
    category: '/product',
    text: `In today's rapidly evolving financial landscape, companies face numerous challenges when it comes to risk management and compliance.`,
    thumbnail: '/images/Home/Blog/3.png',
  },
  {
    title: `Elevating your risk strategy: spektr's solution to smarter decisions`,
    date: 'Oct 4, 2023',
    category: '/product',
    text: `In today's rapidly evolving financial landscape, companies face numerous challenges when it comes to risk management and compliance.`,
    thumbnail: '/images/Home/Blog/1.png',
  },
  {
    title: `It’s time to conduct due diligence differently.`,
    date: 'Oct 4, 2023',
    category: '/product',
    text: `In today's rapidly evolving financial landscape, companies face numerous challenges when it comes to risk management and compliance.`,
    thumbnail: '/images/Home/Blog/2.png',
  },
  {
    title: `It’s time to conduct due diligence differently.`,
    date: 'Oct 4, 2023',
    category: '/product',
    text: `In today's rapidly evolving financial landscape, companies face numerous challenges when it comes to risk management and compliance.`,
    thumbnail: '/images/Home/Blog/3.png',
  },
]
